### ISSUE TITLE
S04E09 翻译指正

### ISSUE THREAD

**Issue by Ntrv777** [fjn308/rm-chs-amzn#6]
11:56  ‘What a fucking mooch’, 这里的mooch是‘白吃、白拿’的意思，意指宙斯窃取rick父女两的劳动成果，建议译作‘真他妈会白嫖！’
17:29  'papa'  means grandpa, 此处应译作‘姥爷’或‘外公’，而不是‘爸爸‘

**Comment by fjn308** [comment]
mooch：这个您说的很有道理，我们的译法意思上是错的，这就去改，多谢！
papa：这个我暂时不认同，我再次确认了下手头的牛津高阶和网上的词典，这个词虽然可能有别的用法，但一般来讲就是“爸爸”了。其实这件事昨天我们内部讨论过，开始给的确实是姥爷这个翻译，后来改成了最直接的爸爸。我们比较倾向的理解是，这俩人吸嗨了说话已经有点胡言乱语了，冒出这么个词，你看他俩平时从来是叫Rick Grandpa的，没这么叫过，要想叫姥爷应该没必要用这个词。

再次感谢！

**Comment by fjn308** [comment]
修改已经体现在GitHub和SubHD的最新字幕里了，第二个来自GitHub的修正，我在片头的字幕信息里标注了您的ID，非常感谢
